export const CARD_ART_WIDTH = 400;
export const CARD_ART_HEIGHT = 680;

export const CARD_ART_ASPECT_RATIO = CARD_ART_WIDTH / CARD_ART_HEIGHT;

export const CARD_ART_HEIGHT_ASPECT = CARD_ART_HEIGHT / CARD_ART_WIDTH;
